### ISSUE TITLE
Upgrade Jetty

### ISSUE THREAD

**Issue by hakko** [hakko/subsonic#1]
Subsonic Jetty version is 6, which is maintenance mode. JSP support is based on jasper 6.0.13 from Apache Tomcat, which doesn't support precompilation of JSPs. (?)

Upgrade Jetty and start using Glassfish support for JSP 2.1 instead, then precompile and trim whitespace.

subsonic-booter/pom.xml:
[groupId]org.eclipse.jetty.aggregate[/groupId]
[artifactId]jetty-all[/artifactId]
[version]7.5.4.v20111024[/version]

[groupId]org.mortbay.jetty[/groupId]
[artifactId]jsp-2.1-glassfish[/artifactId]
[version]2.1.v20100127[/version]

More investigation needed.

**Comment by maxxh** [comment]
I updated the booter code to use Jetty 8.
Here is the patch: http://pastie.org/private/ptyxywhdawfscrpwqojoa
It works here, but i am sure further testing is required.

I did not try to precompile the JSPs in main, so a JDK should be available. Alternatively the embedded compiler in jetty can be used, which can be activated with -Dorg.apache.jasper.compiler.disablejsr199=true

**Comment by hakko** [comment]
Hey, thanks for looking into this!

I'm currently busy with real life/work + another open source project, but I hope to get some time to work on it next weekend. What I plan for the next version (0.7.11) is to clean up some less elegant code and db solutions in MusicCabinet, and add an advanced search view. Upgrading Jetty would go well with the general clean-up idea and it can then be released as a more experimental build for anyone willing to test (running the risk of some initial trouble, but getting the benefits of the advanced search feature). There are normally some early adopters who could help out with this.
